M48
; DRILL file {KiCad 8.0.9} date 2025-03-06T21:03:38+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-06T21:03:38+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0327
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0484
%
G90
G05
T1
X10.0665Y-4.7067
X10.2941Y-4.7067
T2
X8.8799Y-3.0787
X10.1799Y-3.0787
T3
X9.4353Y-4.7315
X9.7493Y-4.7315
T4
X8.8799Y-4.189
X10.1799Y-4.189
M30
